+incdir+$(REPO_HOME)/rtl/coprocessor
+incdir+$(REPO_HOME)/verif/formal
$(REPO_HOME)/rtl/coprocessor/scarv_cop_aes_sbox.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_aes.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_cprs.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_idecode.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_palu.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_palu_adder.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_palu_shifter.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_palu_multiplier.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_malu.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_rng.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_mem.v
$(REPO_HOME)/rtl/coprocessor/scarv_cop_top.v
$(REPO_HOME)/verif/tb/tb_scarv_cop_top.v
